# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cptd/git/AP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cptd/git/AP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cptd/git/AP/CMakeFiles /home/cptd/git/AP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cptd/git/AP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pcd_test

# Build rule for target.
pcd_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcd_test
.PHONY : pcd_test

# fast build rule for target.
pcd_test/fast:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/build
.PHONY : pcd_test/fast

src/Cloud2Serialize.o: src/Cloud2Serialize.cpp.o
.PHONY : src/Cloud2Serialize.o

# target to build an object file
src/Cloud2Serialize.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Cloud2Serialize.cpp.o
.PHONY : src/Cloud2Serialize.cpp.o

src/Cloud2Serialize.i: src/Cloud2Serialize.cpp.i
.PHONY : src/Cloud2Serialize.i

# target to preprocess a source file
src/Cloud2Serialize.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Cloud2Serialize.cpp.i
.PHONY : src/Cloud2Serialize.cpp.i

src/Cloud2Serialize.s: src/Cloud2Serialize.cpp.s
.PHONY : src/Cloud2Serialize.s

# target to generate assembly for a file
src/Cloud2Serialize.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Cloud2Serialize.cpp.s
.PHONY : src/Cloud2Serialize.cpp.s

src/CloudNode.o: src/CloudNode.cpp.o
.PHONY : src/CloudNode.o

# target to build an object file
src/CloudNode.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/CloudNode.cpp.o
.PHONY : src/CloudNode.cpp.o

src/CloudNode.i: src/CloudNode.cpp.i
.PHONY : src/CloudNode.i

# target to preprocess a source file
src/CloudNode.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/CloudNode.cpp.i
.PHONY : src/CloudNode.cpp.i

src/CloudNode.s: src/CloudNode.cpp.s
.PHONY : src/CloudNode.s

# target to generate assembly for a file
src/CloudNode.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/CloudNode.cpp.s
.PHONY : src/CloudNode.cpp.s

src/Euclid.o: src/Euclid.cpp.o
.PHONY : src/Euclid.o

# target to build an object file
src/Euclid.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Euclid.cpp.o
.PHONY : src/Euclid.cpp.o

src/Euclid.i: src/Euclid.cpp.i
.PHONY : src/Euclid.i

# target to preprocess a source file
src/Euclid.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Euclid.cpp.i
.PHONY : src/Euclid.cpp.i

src/Euclid.s: src/Euclid.cpp.s
.PHONY : src/Euclid.s

# target to generate assembly for a file
src/Euclid.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Euclid.cpp.s
.PHONY : src/Euclid.cpp.s

src/GraphSearcher.o: src/GraphSearcher.cpp.o
.PHONY : src/GraphSearcher.o

# target to build an object file
src/GraphSearcher.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/GraphSearcher.cpp.o
.PHONY : src/GraphSearcher.cpp.o

src/GraphSearcher.i: src/GraphSearcher.cpp.i
.PHONY : src/GraphSearcher.i

# target to preprocess a source file
src/GraphSearcher.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/GraphSearcher.cpp.i
.PHONY : src/GraphSearcher.cpp.i

src/GraphSearcher.s: src/GraphSearcher.cpp.s
.PHONY : src/GraphSearcher.s

# target to generate assembly for a file
src/GraphSearcher.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/GraphSearcher.cpp.s
.PHONY : src/GraphSearcher.cpp.s

src/GraphUtil.o: src/GraphUtil.cpp.o
.PHONY : src/GraphUtil.o

# target to build an object file
src/GraphUtil.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/GraphUtil.cpp.o
.PHONY : src/GraphUtil.cpp.o

src/GraphUtil.i: src/GraphUtil.cpp.i
.PHONY : src/GraphUtil.i

# target to preprocess a source file
src/GraphUtil.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/GraphUtil.cpp.i
.PHONY : src/GraphUtil.cpp.i

src/GraphUtil.s: src/GraphUtil.cpp.s
.PHONY : src/GraphUtil.s

# target to generate assembly for a file
src/GraphUtil.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/GraphUtil.cpp.s
.PHONY : src/GraphUtil.cpp.s

src/ProbComp.o: src/ProbComp.cpp.o
.PHONY : src/ProbComp.o

# target to build an object file
src/ProbComp.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/ProbComp.cpp.o
.PHONY : src/ProbComp.cpp.o

src/ProbComp.i: src/ProbComp.cpp.i
.PHONY : src/ProbComp.i

# target to preprocess a source file
src/ProbComp.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/ProbComp.cpp.i
.PHONY : src/ProbComp.cpp.i

src/ProbComp.s: src/ProbComp.cpp.s
.PHONY : src/ProbComp.s

# target to generate assembly for a file
src/ProbComp.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/ProbComp.cpp.s
.PHONY : src/ProbComp.cpp.s

src/Segmentor.o: src/Segmentor.cpp.o
.PHONY : src/Segmentor.o

# target to build an object file
src/Segmentor.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Segmentor.cpp.o
.PHONY : src/Segmentor.cpp.o

src/Segmentor.i: src/Segmentor.cpp.i
.PHONY : src/Segmentor.i

# target to preprocess a source file
src/Segmentor.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Segmentor.cpp.i
.PHONY : src/Segmentor.cpp.i

src/Segmentor.s: src/Segmentor.cpp.s
.PHONY : src/Segmentor.s

# target to generate assembly for a file
src/Segmentor.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Segmentor.cpp.s
.PHONY : src/Segmentor.cpp.s

src/Serializer.o: src/Serializer.cpp.o
.PHONY : src/Serializer.o

# target to build an object file
src/Serializer.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Serializer.cpp.o
.PHONY : src/Serializer.cpp.o

src/Serializer.i: src/Serializer.cpp.i
.PHONY : src/Serializer.i

# target to preprocess a source file
src/Serializer.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Serializer.cpp.i
.PHONY : src/Serializer.cpp.i

src/Serializer.s: src/Serializer.cpp.s
.PHONY : src/Serializer.s

# target to generate assembly for a file
src/Serializer.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Serializer.cpp.s
.PHONY : src/Serializer.cpp.s

src/Viewer.o: src/Viewer.cpp.o
.PHONY : src/Viewer.o

# target to build an object file
src/Viewer.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Viewer.cpp.o
.PHONY : src/Viewer.cpp.o

src/Viewer.i: src/Viewer.cpp.i
.PHONY : src/Viewer.i

# target to preprocess a source file
src/Viewer.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Viewer.cpp.i
.PHONY : src/Viewer.cpp.i

src/Viewer.s: src/Viewer.cpp.s
.PHONY : src/Viewer.s

# target to generate assembly for a file
src/Viewer.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/Viewer.cpp.s
.PHONY : src/Viewer.cpp.s

src/pcd_test.o: src/pcd_test.cpp.o
.PHONY : src/pcd_test.o

# target to build an object file
src/pcd_test.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/pcd_test.cpp.o
.PHONY : src/pcd_test.cpp.o

src/pcd_test.i: src/pcd_test.cpp.i
.PHONY : src/pcd_test.i

# target to preprocess a source file
src/pcd_test.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/pcd_test.cpp.i
.PHONY : src/pcd_test.cpp.i

src/pcd_test.s: src/pcd_test.cpp.s
.PHONY : src/pcd_test.s

# target to generate assembly for a file
src/pcd_test.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_test.dir/build.make CMakeFiles/pcd_test.dir/src/pcd_test.cpp.s
.PHONY : src/pcd_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pcd_test"
	@echo "... rebuild_cache"
	@echo "... src/Cloud2Serialize.o"
	@echo "... src/Cloud2Serialize.i"
	@echo "... src/Cloud2Serialize.s"
	@echo "... src/CloudNode.o"
	@echo "... src/CloudNode.i"
	@echo "... src/CloudNode.s"
	@echo "... src/Euclid.o"
	@echo "... src/Euclid.i"
	@echo "... src/Euclid.s"
	@echo "... src/GraphSearcher.o"
	@echo "... src/GraphSearcher.i"
	@echo "... src/GraphSearcher.s"
	@echo "... src/GraphUtil.o"
	@echo "... src/GraphUtil.i"
	@echo "... src/GraphUtil.s"
	@echo "... src/ProbComp.o"
	@echo "... src/ProbComp.i"
	@echo "... src/ProbComp.s"
	@echo "... src/Segmentor.o"
	@echo "... src/Segmentor.i"
	@echo "... src/Segmentor.s"
	@echo "... src/Serializer.o"
	@echo "... src/Serializer.i"
	@echo "... src/Serializer.s"
	@echo "... src/Viewer.o"
	@echo "... src/Viewer.i"
	@echo "... src/Viewer.s"
	@echo "... src/pcd_test.o"
	@echo "... src/pcd_test.i"
	@echo "... src/pcd_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

